# Generated by Django 2.0.4 on 2018-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180508_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0),
        ),
    ]
